const data = [
  {id: 0,
  question:"Olá visitante, nós do Museu MM Gerdau contamos com sua colaboração respondendo este questionário, para que nossa equipe possa melhorar o espaço para você!",
  answers:["Vamos Lá"]},
  {id: 1,
  question:"Gênero:",
  answers:["Masculino","Feminino","Outros"]},
  {id: 2,
  question:"Faixa Etária:",
  answers:["13 a 19 anos", "20 a 29 anos","30 a 39 anos","40 a 49 anos","50 a 59 anos","60+",]},
  {id: 3,
  question:"Escolaridade:",
  answers:["Sem instrução escolar","Ensino fundamental incompleto", "Ensino Fundamental completo", "Ensino Médio incompleto", "Ensino Médio completo", "Ensino Superior incompleto", " Ensino Superior completo", "Pós-graduação incompleta", "Pós-graduação completa"]},
  {id: 4,
  question:"Em relação à sua cor ou raça/etnia, como você se considera:",
  answers:[" Branca", "Preta", "Parda","Amarela","Indígena","Não desejo informar."]},
  {id: 5,
    question:"Você possui alguma dificuldade ou deficiência permanente, que limite as suas atividades habituais?",
    answers:["Não","Auditiva","Intelectual/mental","Física/motora","Visual"]},
  {id: 6,
  question:"Onde você mora?",
  answers:["BH","Região Metropolitana de BH","Interior de Minas Gerais", "Outro Estado", "Outro País"]},
  {id: 7,
    question:"Em qual faixa de renda, aproximadamente, encontra-se a renda total de sua família por mês?",
    answers:["Zero a 1 Salário Mínimo","Acima de 1 a 2 Salários Mínimos","Acima de 2 a 5 Salários Mínimos","Acima de 5 a 10 Salários Mínimos","Acima de 10 a 20 Salários Mínimos","Acima de 20 Salários Mínimos", "Não desejo informar."]},
  {id: 8,
  question:"Quantas vezes você nos visitou?",
  answers:["1ª Vez","2","3 ou mais"]},
  {id: 9,
    question:"Você veio:",
    answers:["Sozinho","Acompanhado"]},
  {id: 10,
  question:"Como você conheceu o MM Gerdau? Marque quantas opções desejar:",
  answers:["Internet","Redes sociais", "Rádio", "TV", "Jornal impresso","Amigos","Lona na frente do Museu", "Outros:"]},
  {id: 11,
    question:"Por que você veio ao MM Gerdau?",
    answers:["Turismo","Visita com escola","Trabalho escolar","Trabalho acadêmico ", "Ir à Loja","Ir à Cafeteria","Outros:"]},
  {id: 12,
    question:"Quais temas você procura aqui?",
    answers:["Cultura","Minerais","Arquitetura","Ciências", "História","Educação", "Outros:"]},
  {id: 13,
  question:"Marque onde você esteve ou por onde passou(quantas opções desejar):",
  answers:["Piso Liberdade (Exposição Térreo)"," Andar das Minas (Exposição 1º andar)","Andar do Metal (Exposição 2º Andar)"," Exposição Temporária","Evento ou Programação","Loja","Cafeteria","Ateliê Científico", "Banheiro", "Outros:"]},
  {id: 14,
  question:"Como você avalia nossos serviços? HORÁRIO DE FUNCIONAMENTO",
  answers:["ótimo","bom","regular","ruim","péssimo","não sei"]},
  {id: 15,
  question:"Como você avalia nossos serviços? ACESSO (facilidade de transporte, sinalização nas ruas)",
  answers:["ótimo","bom","regular","ruim","péssimo","não sei"]},
  {id: 16,
  question:"Como você avalia nossos serviços? ACESSIBILIDADE DO ESPAÇO FÍSICO",
  answers:["ótimo","bom","regular","ruim","péssimo","não sei"]},
  {id: 17,
  question:"Como você avalia nossos serviços? SINALIZAÇÃO (orientação de entrada, saída, banheiros…)",
  answers:["ótimo","bom","regular","ruim","péssimo","não sei"]},
  {id: 18,
    question:"Como você avalia nossos serviços? CONFORTO (banheiros, guarda volumes, temperatura das salas…)",
    answers:["ótimo","bom","regular","ruim","péssimo","não sei"]},
  {id: 19,
    question:"Como você avalia nossos serviços? CONSERVAÇÃO (das exposições, dos equipamentos e objetos expostos…)",
  answers:["ótimo","bom","regular","ruim","péssimo","não sei"]},
  {id: 20,
    question:"Como você avalia nossos serviços? LIMPEZA",
    answers:["ótimo","bom","regular","ruim","péssimo","não sei"]},
  {id: 21,
    question:"Como você avalia nossos serviços? ILUMINAÇÃO",
  answers:["ótimo","bom","regular","ruim","péssimo","não sei"]},
  {id: 22,
    question:"Como você avalia nossos serviços? SEGURANÇA",
    answers:["ótimo","bom","regular","ruim","péssimo","não sei"]},
  {id: 23,
    question:"Como você avalia nossos serviços? ACOLHIMENTO (recepção, mediadores…)",
  answers:["ótimo","bom","regular","ruim","péssimo","não sei"]},
  {id: 24,
    question:"Como você avalia nossos serviços? INFORMAÇÕES SOBRE AS EXPOSIÇÕES (totens, painéis, textos, filmes…)",
  answers:["ótimo","bom","regular","ruim","péssimo","não sei"]},
  {id: 25,
    question:"Como você avalia nossos serviços? HORÁRIO DE FUNCIONAMENTO",
  answers:["ótimo","bom","regular","ruim","péssimo","não sei"]},
  {id: 26,
    question:"Como você avalia nossos serviços? HORÁRIO DE FUNCIONAMENTO",
  answers:["ótimo","bom","regular","ruim","péssimo","não sei"]},
  {id: 27,
    question:"Como você avalia nossos serviços? HORÁRIO DE FUNCIONAMENTO",
  answers:["ótimo","bom","regular","ruim","péssimo","não sei"]},
  {id: 28,
    question:"Como você avalia nossos serviços? HORÁRIO DE FUNCIONAMENTO",
  answers:["ótimo","bom","regular","ruim","péssimo","não sei"]},

]
export default data